-- create table type_in_menu(
-- 	id int auto_increment primary key,
-- 	type varchar(50),
-- 	id_product int
-- );
-- create table products(
-- 	id int auto_increment primary key,
-- 	product varchar(50) not null,
-- 	description mediumtext,
--   price decimal(5,2) not null
-- );
-- create table sub_types(
-- 	id int auto_increment primary key,
-- 	sub_type varchar(50) not null
-- -- );
-- ALTER TABLE menu_list
-- ADD CONSTRAINT product
-- FOREIGN KEY (id_product) REFERENCES products(id);
-- create table sub_list(
-- 	id int auto_increment primary key,
-- 	id_menu_item decimal(5,2) not null,
-- 	sub_item varchar(100) not null
-- );
-- create table news_feed(
--   id int auto_increment primary key,
--   img_url varchar(500),
--   title mediumtext
-- );
-- alter table news_feed
-- add column id_option INT(11);
